services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB_NAME=inventario_directory
      - DB_USERNAME=hameed
      - DB_PASSWORD=hameed
      - SECRETE_KEY=1YYdxLhupIOVymRE6S4sb3Da2oX466XEoqiloczT94k=
#    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario_directory
      MYSQL_USER: hameed
      MYSQL_PASSWORD: hameed
    ports:
      - 3306:3306
#    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql

volumes:
  db_data:
