services:
  inventario-backend-app:
    image: pshameed/inventario-backend-app:1.1
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - 8080:8080
#    restart: always
    depends_on:
      - inventario-db

  inventario-db:
    image: mysql:8.4
    env_file:
      - .env
    ports:
      - 3306:3306
#    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql

volumes:
  db_data:
