type: object
properties:
  id:
    type: integer
    format: int64
    description: Unique identifier representing a specific product
    readOnly: true
  productName:
    type: string
    description: Full Name of the Product
    example: "TestProductName"
  productCode:
    type: string
    description: Short Code to identify the product
    example: "PROD01"
  description:
    type: string
  barcode:
    type: string
  currentPrice:
    type: number
    format: double
  currentCost:
    type: number
    format: double
  quantity:
    type: integer
    format: int32
  imageUrl:
    type: string
    format: URI
  category:
    $ref: "../basic/CategoryDTO.yaml"
  primaryUom:
    $ref: "../basic/UnitOfMeasureDTO.yaml"
  creationDate:
    $ref: "../../common/iso_timestamp.yaml"
  lastUpdateDate:
    $ref: "../../common/iso_timestamp.yaml"
  createdBy:
    type: string
    description: The userEntity who created this product. This is only accessible to authorized users.
    readOnly: true
    nullable: true
  lastUpdateBy:
    type: string
    description: The last userEntity who modified this product. This is only accessible to authorized users.
    readOnly: true
    nullable: true